version: '3.8'

services:
  vulnerable_website:
    image: vulnerable-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: vulnerable_website_container
