services:
  unvulnerable_website:
    image: unvulnerable-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: vulnerable_website_container
    depends_on:
      - sql_server

  sql_server:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=N1astya_
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/data:/var/opt/mssql

volumes:
  sql_data:
